### ISSUE TITLE
Heroku build fails

### ISSUE THREAD

**Issue by stoneric** [AugurProject/augur-node#192]
The Heroku button / build not working.

![screen shot 2018-02-13 at 8 34 25 am](https://user-images.githubusercontent.com/6919202/36161542-d2f7523c-1098-11e8-8fe8-1701d7769fcd.png)

**Comment by pgebheim** [comment]
Yes, indeed. We should remove this for now until we can do another heroku pass. I've made a [clubhouse issue](https://app.clubhouse.io/augur/story/7022/remove-deploy-to-heroku-button-until-it-functions-again) to handle this.

**Comment by pgebheim** [comment]
Removed the heroku deploy link for now.
