### ISSUE TITLE
How to Run Everything on Localhost

### ISSUE THREAD

**Issue by abhishek8298** [AugurProject/augur-node#502]
I cloned this package:https://github.com/AugurProject/augur-node.git
Installed It By npm install
Now when i start it, it runs on localhost:8080

It Redirects me to:http://localhost:8080/#/categories
Where there are 2 columns:
CONNECT TO AUGUR VIA
AUGUR NODE ADDRESS:

ws://127.0.0.1:9001
ETHEREUM NODE ADDRESS:

ws://127.0.0.1:8546

When I tap on Connect it shows this message:!
There was an issue connecting to the nodes, please try again.

Can anyone tell me how to connect to these?or which are more packages to be cloned?and how to deploy them!
Please Help Asap.

**Comment by bthaile** [comment]
This probably is simple, just need more information on your setup. 
Come to discord, pop into the dev channel. 

https://www.augur.net

There is a link ‘find us on discord’

**Comment by sharkcrayon** [comment]
@abhishek8298 Have you had any luck with this? Feel free to come chat in the Augur Discord. Invite link: https://discord.gg/faud6Fx

**Comment by bthaile** [comment]
We moved the conversation to discord #dev
His main issue was docker installed, we pointed him to the mac docker installer. He is good to go. I'm going to close this.

**Comment by bthaile** [comment]
I'm going to close this, issue resolved.
