### ISSUE TITLE
Augur Node should put DB file(s) into their own folder.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-node#543]
When deploying to the cloud with docker, if you want to persist something to local disk you generally do it by mounting a folder in the container to a folder on the host system.  With Augur, the DB is stored in the root folder along with a bunch of other files that should not be persisted, and are not regenerated when the container is launched.  This means if you mount the folder containing the DB file you end up deleting all of the files used to run the Augur Node.

This is a simple config change (where to store file on disk, could be done optionally and implemented in the Dockerfile.

**Comment by pgebheim** [comment]
This can be set now with the DATABASE_DIR environment variable.
