### ISSUE TITLE
augur-node breaks if you have $DATABASE_URL set

### ISSUE THREAD

**Issue by TristanH** [AugurProject/augur-node#558]
Right now, it seems that postgres does not work and is not used. However, if you happen to have `$DATABASE_URL` set (I did), augur-node still tries to use postgres and breaks:

https://github.com/AugurProject/augur-node/blob/3be6f8df5e8a94fe2b32700e24eab75345b80772/src/setup/check-and-initialize-augur-db.ts#L35

The breakage is very annoying and cost me an hour or so, because it's quite hard to figure out why you're getting a SQL error!

Perhaps this line should just be an `if(false)` instead?

However, it seems that [this PR](https://github.com/AugurProject/augur-node/pull/294) might be re-enabling postgres, so maybe it's worth just ignoring and waiting until then?

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14663/github-augur-node-breaks-if-you-have-database-url-set

**Comment by ndbroadbent** [comment]
Is it true that Postgres support is currently broken and the only supported database is SQLite?

**Comment by pgebheim** [comment]
We've merged in PGSQL support, it should indeed be working. As of yesterday I was able to fully sync/use a UI against augur node.

One known issue is that FTS search doesnt quite work as expected.

Please report any other issues so we can take a look! We'll be updating our dev/test environments to have Postgres backed augur nodes for continuous testing over the next couple weeks.

**Comment by pgebheim** [comment]
@TristanH -- This should be working now since we've merged in postgresql support.

Please try again!
