### ISSUE TITLE
Fetched 0 / 5 block details (current: 0)

### ISSUE THREAD

**Issue by SirLancelot-OG** [AugurProject/augur-node#640]
Running the latest version of the repo - I believe 5.7.0. Having lots of trouble syncing. Running Ubuntu 18.04.

Running `npm clean-start`

Data is not recorded to the DB and the following is printed every so often:
`Fetched 0 / 5 block details (current: 0)`

Endpoints:
```
{
    "http":"https://mainnet.infura.io/v3/63a0f7e8ffc64c00c855c4faa2fe2b1",
    "ws":"wss://mainnet.infura.io/ws"
}
```

I should add that I have also run augur.deb on this server, but it is not running at the same time.

**Comment by adrake33** [comment]
@SirLancelot-OG Infura is not very reliable. Please try using one of the endpoints listed at https://predictions.global/augur-public-ethereum-nodes and let us know if you're still seeing the error.

**Comment by SirLancelot-OG** [comment]
Thanks Aaron, fetching blocks properly using `https://gethnode.com/http` and `wss://gethnode.com/ws` endpoints.
