### ISSUE TITLE
Suggestion: `getFeeWindow()` could also return the total number of participation tokens

### ISSUE THREAD

**Issue by veox** [AugurProject/augur-node#667]
[The getter in question](https://github.com/AugurProject/augur-node/blob/680bd6d5db0632f569cb237119d67db28ad36a99/src/server/getters/get-fee-window.ts#L98) currently returns a given window's "ETH fees" and "REP staked".

IIUC, the latter is REP that's participating in a dispute, on some particular outcome.

It "would be nice" to be able to find out the total number of participation tokens (that aren't otherwise involved in disputes), e.g. as was [asked in this market](https://predictions.global/augur-markets/will-more-than-65000-participation-tokens-be-utilized-in-the-fee-window-ending-closest-to-september-5th-2018-0xbb92464f40a10d3a6b5755d4abaf3436d66cce8a).

Currently, it's possible to specify a `reporter` when calling `getFeeWindow()`, which populates the response with additional fields, but only pertaining to that `reporter`.

**Comment by adrake33** [comment]
Added this issue to our internal tracking system: https://app.clubhouse.io/augur/story/17195/github-getfeewindow-could-also-return-the-total-number-of-participation-tokens

**Comment by epheph** [comment]
https://github.com/AugurProject/augur-node/pull/670

**Comment by adrake33** [comment]
Closing this issue since it is addressed in the PR above.
