### ISSUE TITLE
Error when syncing with Postgres

### ISSUE THREAD

**Issue by mattxsmith** [AugurProject/augur-node#714]
When syncing with Postgres, the new table _transactionHashes_ is causing an error:

`select * from "transactionHashes" where "transactionHash" = $1 - relation "transactionHashes" does not exist`

I realized this is an error due to the way Postgres is capitalizing the table name. When syncing, the query is looking for a table with a capital H: _transactionHashes_. When you look at the actual table created, there is no capitalization: _transactionhashes_. 

This can be fixed by adding double quotes around _transactionHashes_ on line 5 in src/migrations/20181109151249_transactionHashes.ts.

**Comment by adrake33** [comment]
Created a ticket for this in our internal tracking system: https://app.clubhouse.io/augur/story/18149/github-error-when-syncing-with-postgres

**Comment by adrake33** [comment]
Closing this since a fix has been merged.
