### ISSUE TITLE
Fix Volume calculations

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur-node#740]
Currently the volume calculations in Augur Node are done by taking the trade amount multiplied by the trade price and summing that with previous volume.

Instead when we update the volumetrics we should increase overall volume by:

- (The lowest of makerSharesProvided and takerSharesProvided) * numTicks
- makerTokensProvided
- takerTokensProvided

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #302](https://github.com/AugurProject/augur/issues/302) via [**ZenHub**](https://www.zenhub.com/)

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #303](https://github.com/AugurProject/augur/issues/303) via [**ZenHub**](https://www.zenhub.com/)
