### ISSUE TITLE
Rename transactionHashes table to transaction_hashes

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-node#741]
(Copying from CH.)

The first is out of style and doesnt work correctly in postgres

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur-node/pull/728

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #301](https://github.com/AugurProject/augur/issues/301) via [**ZenHub**](https://www.zenhub.com/)
