### ISSUE TITLE
Return trade data from Augur Node for trading page redesign

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-node#750]
In order to implement the new Trade History (https://github.com/AugurProject/augur/issues/724) & Filled Orders (https://github.com/augurproject/augur/issues/731) sections of the trading page redesign, Augur Node will need to be modified.

Tom proposed the following spec for the data returned by a new Augur Node endpoint in the comments of https://github.com/AugurProject/augur/issues/724. (This data would be sorted by timestamp in descending order, and the UI would then do the grouping of these orders by date, since it is dependent on the user's local time.)
```
marketId:[ {
amount,
price,
timestamp,
outcome,
orderType,
filler,
creator,
tradeGroupId
}]
```
Alternatively, this info could be returned by an existing endpoint if that would make more sense.

**Comment by adrake33** [comment]
Which function(s) are you referring to? Phoebe had asked if we could get this info from AN, and when I suggested using augur.trading.getUserTradingHistory, she pointed out that it doesn't indicate if the order is filled, and it doesn't group the trades in the way we'd like.

**Comment by bthaile** [comment]
There is a endpoint to get market price history. ‘getMarketPriceHistory’ its used in the UI, not sure what for but we can extend it to include more fields. It could be used for filled orders and user trades without all the PL position extra stuff.

**Comment by adrake33** [comment]
@epheph If you are still planning to work on some things during the break next week, please work on this task first, since it is required by 2 tasks for the trading page redesign (which we are still hoping to launch 2 weeks before the Super Bowl). It's been updated with the spec Tom provided.

**Comment by adrake33** [comment]
Fixed by https://github.com/AugurProject/augur-node/pull/757
