### ISSUE TITLE
Syncing fails with no error

### ISSUE THREAD

**Issue by mikemcdonald** [AugurProject/augur-node#764]
```Fetched 10 / 29 block details (current: 6352822)
Fetched 20 / 29 block details (current: 6352987)
Fetching blocks details from 6353284 to 6353977
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@7.2.0 start: ts-node ./src/runServer
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the augur-node@7.2.0 start script.
```

This is the only error shown when `npm run clean-start` is run. Always seems to fail somewhere between block 6350000 6360000. Running this on OSX with a local postgres database.

parity 2.1.10 with --no-warp
node v10.12.0

**Comment by adrake33** [comment]
Assigning to @pgebheim for now since he and mikemcdonald were discussing this on Discord yeterday. This issue is happening on mainnet for him, and he said:
```
i think all the initial migrations run correctly, at least i can see all of the tables
but no rows are added for blocks and what not even after running for about 30 seconds and then finally exiting
```

**Comment by mikemcdonald** [comment]
Through trial and error I found this issue is related to https://github.com/AugurProject/augur-app/issues/291 . My parity node is synced with no-warp, but I will try deleting the database and syncing from scratch again
